export enum NotificationType {
    GENERAL = 'GENERAL',
    ASSIGNMENT = 'ASSIGNMENT',
    DISCUSSION = 'DISCUSSION',
    VIDEO_SESSION = 'VIDEO_SESSION',
    JOIN_REQUEST = 'JOIN_REQUEST',
    JOIN_APPROVED = 'JOIN_APPROVED',
    JOIN_REJECTED = 'JOIN_REJECTED',
}
